{{- if .Values.istio.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-distributed-tracing
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: jaeger
  source: community-operators
  sourceNamespace: openshift-marketplace
{{ end }}