{{- if .Values.istio.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
  namespace: openshift-distributed-tracing
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    exporters:
      otlp:
        endpoint: "jaeger-all-in-one-inmemory-otlp-grpc.openshift-distributed-tracing.svc:4317"
        tls:
          insecure: true

      debug: {}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp, debug]

  jaeger:
    spec:
      strategy: allInOne
      allInOne:
        image: "quay.io/jaegertracing/all-in-one:latest"
        options:
          query:
            base-path: /
      storage:
        type: memory
        options:
          memory:
            max-traces: 100000
      ingress:
        enabled: true
{{ end }}